# Generated by Django 4.1.1 on 2022-09-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NavigationElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_name", models.CharField(max_length=15)),
                ("is_cta", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="SectionAboutUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("about_us_subheading", models.CharField(max_length=15)),
                ("about_us_primary_heading", models.CharField(max_length=70)),
                ("about_us_content", models.TextField()),
                ("about_us_circle_animation", models.BooleanField(default=True)),
                ("about_us_image_url", models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="SectionCTA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cta_primary_heading", models.CharField(max_length=70)),
                ("cta_description", models.CharField(max_length=250)),
                ("where_found_options", models.JSONField()),
                ("image_animation", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="SectionDepartments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("departments_subheading", models.CharField(max_length=25)),
                ("departments_primary_heading", models.CharField(max_length=70)),
                ("department_icon_animation", models.BooleanField(default=True)),
                ("departments", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="SectionFeaturedInGeneral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("featured_in_title", models.CharField(max_length=40)),
                ("featured_in_visibility", models.BooleanField(default=True)),
                ("featured_in_logos_gap", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="SectionFeaturedInLogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("logo_name", models.CharField(max_length=50)),
                ("logo_url", models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="SectionFooter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("social_icons", models.JSONField()),
                ("address_line", models.CharField(max_length=100)),
                ("tel_line", models.CharField(max_length=15)),
                ("mail_line", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="SectionHero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hero_title", models.CharField(max_length=40)),
                ("hero_description", models.CharField(max_length=216)),
                ("hero_bg", models.CharField(max_length=20)),
                ("left_button_displayed", models.BooleanField(default=True)),
                ("right_button_displayed", models.BooleanField(default=True)),
                ("left_button_content", models.CharField(max_length=15)),
                ("right_button_content", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="SectionTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_subheading", models.CharField(max_length=25)),
                ("team_primary_heading", models.CharField(max_length=70)),
                ("team", models.JSONField()),
            ],
        ),
    ]
